# Generated by Django 6.0.1 on 2026-01-25 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
    ]
