# Generated by Django 6.0.1 on 2026-01-25 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('player', '0002_auto_20260125_1209'),
        ('user', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='player_profile', serialize=False, to='user.appuser')),
                ('elo', models.DecimalField(decimal_places=2, default=1500.0, help_text='Elo rating', max_digits=6)),
                ('glicko', models.DecimalField(decimal_places=2, default=1500.0, help_text='Glicko rating', max_digits=6)),
                ('glicko_rd', models.DecimalField(decimal_places=2, default=350.0, help_text='Rating Deviation', max_digits=6)),
                ('volatility', models.DecimalField(decimal_places=8, default=0.06, help_text='Volatility', max_digits=10)),
                ('tries', models.IntegerField(default=0, help_text='Total number of games played')),
                ('last_game_date', models.DateTimeField(blank=True, help_text='Date of last game played', null=True)),
            ],
            options={
                'db_table': 'player',
            },
        ),
    ]
