# Generated by Django 5.0.6 on 2026-01-27 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='gamecount',
            field=models.IntegerField(default=0, help_text='Total number of games played'),
        ),
    ]
