# Generated by Django 6.0.1 on 2026-01-25 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='admin_profile', serialize=False, to='user.appuser')),
                ('permissions_level', models.IntegerField(default=1, help_text='Level of admin permissions')),
            ],
        ),
    ]
