# Generated by Django 6.0.1 on 2026-01-25 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_auto_20260125_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('user_id', models.AutoField(db_column='user_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=100)),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('PLAYER', 'Player')], db_column='role', max_length=10)),
                ('password', models.CharField(db_column='password_hash', max_length=255)),
            ],
            options={
                'db_table': 'app_user',
                'managed': False,
            },
        ),
    ]
